### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by xKumorio** [kugge/Kaiiju#49]
### Expected behavior

No kicking

### Observed/Actual behavior

Kicks me and the players next to me

### Steps/models to reproduce

Any action with the shulkers. This is not a stash optimization patch because I checked without it.

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/78680226/232881868-73a9de74-2b54-40df-8ea0-0001ecfa23ec.png)
Also tested without plugins

### Kaiiju version

Latest Kaiju + stash optimization by XYMB

### Other

[22:10:22] [Netty Epoll Server IO #2/ERROR]: Packet encoding of packet ID 82 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:473) ~[?:?]
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:21) ~[?:?]
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:473) ~[?:?]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:716) ~[kaiiju-1.19.4.jar:git-Kaiiju-"9a509f2"]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:704) ~[kaiiju-1.19.4.jar:git-Kaiiju-"9a509f2"]
	at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:690) ~[?:?]
	at net.minecraft.network.syncher.EntityDataSerializers$1.write(EntityDataSerializers.java:45) ~[?:?]
	at net.minecraft.network.syncher.EntityDataSerializers$1.copy(EntityDataSerializers.java:42) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData$DataValue.write(SynchedEntityData.java:351) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:18) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[kaiiju-1.19.4.jar:git-Kaiiju-"9a509f2"]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[kaiiju-1.19.4.jar:git-Kaiiju-"9a509f2"]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:126) ~[TAB-4.0.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:486) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:460) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:10:22] [RegionFile I/O Thread #0/INFO]: [STDOUT] [xymb.NBTDeduplicator] anarchyOptimization! <world -22358 14944>
[22:10:22] [Region Scheduler Thread #1/INFO]: _Soft1k_ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
[22:10:22] [Region Scheduler Thread #1/INFO]: _Soft1k_ left the game

**Comment by xymb-endcrystalme** [comment]
1) This is not a Kaiiju bug as stash optimization is **not** in Kaiiju. Thus the bug doesn't fit here.
I won't push stash optimizations upstream until it's deployed for a week on `6b6t.org`.

2) You need to include how to reproduce the bug. Provide some instructions & files necessary. We're not clairvoyants.
