### ISSUE TITLE
Region #147924 centered at chunk [2346, 1802] in world 'world' failed to tick

### ISSUE THREAD

**Issue by starmc63** [kugge/Kaiiju#72]
### Expected behavior

no crash

### Observed/Actual behavior

server crashed

### Steps/models to reproduce

teleport to another world

### Plugin and Datapack List

[15:50:52 INFO]: Server Plugins (31):
[15:50:52 INFO]: Paper Plugins:
[15:50:52 INFO]: - HuskHomes
[15:50:52 INFO]: Bukkit Plugins:
[15:50:52 INFO]: - AmazingBot, Attollo, BBeeChecker, BetterRTP, BlockLocker, Chunky, CodFrame, CoreProtect, FastAsyncWorldEdit, FoliaFlow
[15:50:52 INFO]: FreedomChat, GreenChunk, GSit, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, Kaiivoid, LuckPerms, MiniMOTD, P
anilla
[15:50:52 INFO]: PlaceholderAPI, PlasmoVoice, TAB, Towny, TownyChat, TownyFlight, TownyMenus, Vault, ViaBackwards, ViaVersion

### Kaiiju version

[15:50:33 INFO]: Checking version, please wait...
[15:50:34 INFO]: This server is running Kaiiju version git-Kaiiju-"349ae3b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Gi
t: 349ae3b on ver/1.20.1)
You are running the latest version
Previous version: git-Kaiiju-"8c562b0" (MC: 1.20.1)

### Other

   [15:39:01] [Region Scheduler Thread #5/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #147924 centered at chunk [2346, 1802] in world 'world' failed to tick:
  | java.lang.IllegalStateException: World mismatch: expected world_nether but got world
  | at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:284) ~[?:?]
  | at net.minecraft.world.level.Level.getDayTime(Level.java:1306) ~[?:?]
  | at net.minecraft.server.level.ServerPlayer.getPlayerTime(ServerPlayer.java:2907) ~[?:?]
  | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[kaiiju-1.20.1.jar:git-Kaiiju-"349ae3b"]
  | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"349ae3b"]
  | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"349ae3b"]
  | at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"349ae3b"]
  | at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"349ae3b"]
  | at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"349ae3b"]
  | at java.lang.Thread.run(Thread.java:1623) ~[?:?]
  | [15:39:01] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
  | [15:39:01] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
  | [15:39:01] [Region shutdown thread/INFO]: Stopping server

**Comment by sofianedjerbi** [comment]
Solved by Folia
