### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by DCE-114514** [kugge/Kaiiju#74]
### Expected behavior

fix the problem

### Observed/Actual behavior

[13:40:14 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #16254 centered at chunk [-775, 1044] in world 'world' faile
d to tick:
java.lang.IllegalStateException: World mismatch: expected world_nether but got world
        at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:284) ~[?:?]
        at net.minecraft.world.level.Level.getDayTime(Level.java:1306) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.getPlayerTime(ServerPlayer.java:2907) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[kaiiju-1.20.1.jar:git-Kaiiju-"6657b9c"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"6657b9c"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"6657b9c"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Ka
iiju-"6657b9c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.j
ar:git-Kaiiju-"6657b9c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.ja
r:git-Kaiiju-"6657b9c"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Steps/models to reproduce

normal play 

### Plugin and Datapack List

Server Plugins (15):
 Bukkit Plugins:
 AmazingBot, AntiPopup, BetterRTP, Chunky, CoreProtect, Essentials, EssentialsChat, FoliaFlow, FreedomChat, GSit
 LuckPerms, PlaceholderAPI, ProtocolLib, RayTraceAntiXray, Vault

### Kaiiju version

This server is running Kaiiju version git-Kaiiju-"1f0e0e1" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Gi
t: 1f0e0e1 on ver/1.20.1)
You are running the latest version
Previous version: git-Kaiiju-"6657b9c" (MC: 1.20.1)

**Comment by sofianedjerbi** [comment]
It seems that this occur on teleportation, can we have more context ? Teleportation type, origin + destination..

**Comment by tuanzisama** [comment]
The same bug still  happened in @DCE-114514 's survival server.
Look like throw by plugin [`FoliaFlow`](https://github.com/Hynse/FoliaFlow).
When player trying to duplicate sand/anvil (or somethings...) and that plugin will persistently throwing exceptions.

Suspected same issues: https://github.com/PaperMC/Folia/issues/23
<details>
  <summary>Exception details</summary>
  
```
[Region Scheduler Thread #9/ERROR]: Could not pass event EntityChangeBlockEvent to FoliaFlow v2.2
java.lang.IllegalStateException: World mismatch: expected world_the_end but got world
	at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:284) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:899) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at xyz.hynse.foliaflow.watcher.PortalWatcher.onFallingBlockToBlock(PortalWatcher.java:29) ~[FoliaFlow-2.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"1f0e0e1"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1352) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1344) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at net.minecraft.world.entity.item.FallingBlockEntity.tick(FallingBlockEntity.java:205) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1380) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1046) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:856) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:544) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:828) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1676) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```
</details>

**Comment by sofianedjerbi** [comment]
> The same bug still  happened in @DCE-114514 's survival server.
> Look like throw by plugin [`FoliaFlow`](https://github.com/Hynse/FoliaFlow).
> When player trying to duplicate sand/anvil (or somethings...) and that plugin will persistently throwing exceptions.
> 
> Suspected same issues: https://github.com/PaperMC/Folia/issues/23
> <details>
>   <summary>Exception details</summary>
>   
> ```
> [Region Scheduler Thread #9/ERROR]: Could not pass event EntityChangeBlockEvent to FoliaFlow v2.2
> java.lang.IllegalStateException: World mismatch: expected world_the_end but got world
> 	at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:284) ~[?:?]
> 	at net.minecraft.world.level.Level.getBlockState(Level.java:899) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at xyz.hynse.foliaflow.watcher.PortalWatcher.onFallingBlockToBlock(PortalWatcher.java:29) ~[FoliaFlow-2.2.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"1f0e0e1"]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1352) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1344) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at net.minecraft.world.entity.item.FallingBlockEntity.tick(FallingBlockEntity.java:205) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1380) ~[?:?]
> 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1046) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:856) ~[?:?]
> 	at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:544) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:828) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1676) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
> 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
> ```
> </details>

Kaiiju already include sand duping config, don't use FoliaFlow

**Comment by sofianedjerbi** [comment]
Not enough information to fix
