### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DCE-114514** [kugge/Kaiiju#75]
### Expected behavior

fix

### Observed/Actual behavior

Chain link failed, continuing to next one
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2213) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.sendPlayerChatMessage(ServerGamePacketListenerImpl.java:2797) ~[?:?]
        at net.minecraft.network.chat.OutgoingChatMessage$Player.sendToPlayer(OutgoingChatMessage.java:48) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.sendChatMessage(ServerPlayer.java:2382) ~[?:?]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.sendNative(ChatProcessor.java:346) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1
f0e0e1"]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.broadcastToViewers(ChatProcessor.java:294) ~[kaiiju-1.20.1.jar:git-K
aiiju-"1f0e0e1"]
        at io.papermc.paper.adventure.ChatProcessor$ViewersOutgoingChat.sendMessageChanged(ChatProcessor.java:283) ~[kaiiju-1.20.1.jar:git-K
aiiju-"1f0e0e1"]
        at io.papermc.paper.adventure.ChatProcessor$OutgoingChat.sendFormatChangedViewerUnaware(ChatProcessor.java:248) ~[kaiiju-1.20.1.jar:
git-Kaiiju-"1f0e0e1"]
        at io.papermc.paper.adventure.ChatProcessor.complete(ChatProcessor.java:231) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
        at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:195) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:121) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2446) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2604) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$14(ServerGamePacketListenerImpl.java:2276) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f0e0e1"
]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f
0e0e1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[kaiiju-1.20.1.jar:git-Kaiiju-"1f
0e0e1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:204) ~[kaiiju-1.20.1.jar:g
it-Kaiiju-"1f0e0e1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:168) ~[kaiiju-1.20.1.jar:git
-Kaiiju-"1f0e0e1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:137) ~[kaiiju-1.20.1.jar:git
-Kaiiju-"1f0e0e1"]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:558) ~[ProtocolLib.j
ar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib
.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:463) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:571) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:535) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:427) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2205) ~[?:?]
        ... 19 more

### Steps/models to reproduce

normal play

### Plugin and Datapack List

Server Plugins (15):
[13:59:26 INFO]: Bukkit Plugins:
[13:59:26 INFO]:  - AmazingBot, AntiPopup, BetterRTP, Chunky, CoreProtect, Essentials, EssentialsChat, FoliaFlow, FreedomChat, GSit
[13:59:26 INFO]:  LuckPerms, PlaceholderAPI, ProtocolLib, RayTraceAntiXray, Vault

### Kaiiju version

This server is running Kaiiju version git-Kaiiju-"1f0e0e1" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Gi
t: 1f0e0e1 on ver/1.20.1)
You are running the latest version
Previous version: git-Kaiiju-"6657b9c" (MC: 1.20.1)

**Comment by sofianedjerbi** [comment]
Plugin issue

**Comment by DCE-114514** [comment]
> Plugin issue

thanks
