### ISSUE TITLE
The server cannot start when your kaiiju-entity-limits. myl file looks like this

### ISSUE THREAD

**Issue by JSWuMing** [kugge/Kaiiju#77]
### Expected behavior

# Per region entity limits for Kaiiju.
# If there are more of particular entity type in a region than limit, entity ticking will be throttled.
# Example: for Wither limit 100 & 300 Withers in a region -> 100 Withers tick every tick & every Wither ticks every 3 ticks.
Wither:
  limit: 1000
  removal: 5000
Axolotl:
  limit: 1000
  removal: 5000

### Observed/Actual behavior

[01:08:04] [Server thread/WARN]: [!] The timings system cannot be enabled on Folia, and has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[01:08:04] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 12 worker threads, and gen parallelism of 12 threads
[01:08:04] [Server thread/INFO]: [io.papermc.paper.threadedregions.TickRegions] Regionised ticking is enabled with 6 tick threads
[01:08:04] [Server thread/ERROR]: Could not load kaiiju_entity_limits.yml, please correct your syntax errors
org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 6, column 1:
    GlowSquid:
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at dev.kaiijumc.kaiiju.KaiijuEntityLimits.init(KaiijuEntityLimits.java:63) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at dev.kaiijumc.kaiiju.KaiijuEntityLimits.init(KaiijuEntityLimits.java:50) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:229) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 6, column 1:
    GlowSquid:
    ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:251) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.0.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 8 more
[01:08:04] [Server thread/ERROR]: Unable to load entity limits
java.lang.RuntimeException: org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 6, column 1:
    GlowSquid:
    ^

	at com.google.common.base.Throwables.propagate(Throwables.java:242) ~[guava-31.1-jre.jar:?]
	at dev.kaiijumc.kaiiju.KaiijuEntityLimits.init(KaiijuEntityLimits.java:66) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at dev.kaiijumc.kaiiju.KaiijuEntityLimits.init(KaiijuEntityLimits.java:50) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:229) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 6, column 1:
    GlowSquid:
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at dev.kaiijumc.kaiiju.KaiijuEntityLimits.init(KaiijuEntityLimits.java:63) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	... 5 more
Caused by: org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<block mapping start>'
 in 'reader', line 6, column 1:
    GlowSquid:
    ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:251) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.0.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at dev.kaiijumc.kaiiju.KaiijuEntityLimits.init(KaiijuEntityLimits.java:63) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	... 5 more
[01:08:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[kaiiju-1.20.1.jar:git-Kaiiju-"589b5f6"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:08:05] [Server thread/ERROR]: This crash report has been saved to: C:\qianren\kaiiju\.\crash-reports\crash-2023-07-10_01.08.05-server.txt
[01:08:05] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[01:08:05] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[01:08:05] [Region shutdown thread/INFO]: Stopping server
[01:08:05] [Region shutdown thread/INFO]: [RegionShutdownThread] Halting chunk systems
[01:08:05] [Region shutdown thread/INFO]: [RegionShutdownThread] Halted chunk systems
[01:08:05] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving players
[01:08:05] [Region shutdown thread/INFO]: Flushing Chunk IO
[01:08:05] [Region shutdown thread/INFO]: Closing Thread Pool
[01:08:05] [Region shutdown thread/INFO]: Closing Server

### Steps/models to reproduce

i dont know

### Plugin and Datapack List

null

### Kaiiju version

null

**Comment by sofianedjerbi** [comment]
This is unreadable, please put logs/stacktrace/config file in a code block:

```
```text```
```

**Comment by xymb-endcrystalme** [comment]
I agree, it's unreadable. But ultimately the reason is listed: `Could not load kaiiju_entity_limits.yml, please correct your syntax errors`

Remove `kaiiju_entity_limits.yml` and modify it from scratch. `.yml` files are very sensitive when it comes to syntax.

**Comment by xymb-endcrystalme** [comment]
And IMO it's better to crash when a config file is broken than to run with a wrong config file and just "assume" configuration.

**Comment by JSWuMing** [comment]
ok thinks~~~

**Comment by JSWuMing** [comment]
sorry it was my carelessness
have already been solved
————————————
抱歉，是我的疏忽
已经解决了
————————————
I can not speak English 
So I've been using Google Translate
————————————
我不会英语 
所以一直使用的谷歌翻译
