### ISSUE TITLE
Problem with entity exception in version 1.20.2

### ISSUE THREAD

**Issue by aweibuome** [kugge/Kaiiju#95]
### Expected behavior

Normal number of entities

### Observed/Actual behavior

Too many entities, including cows, sheep, water creatures, zombie, and so on

### Steps/models to reproduce

When I set the per-player-mob-spawns option in the paper-world-defaults.yml configuration file to true, although the server only has a few players online, the number of entities in an area has reached an astonishing 20,000 , cows, horses, and squids everywhere, it is impossible to kill them all. This problem does not exist in version 1.20.1. The monster spawning limit in the Bukkit configuration file is the default. When I set the per-player-mob-spawns option to false, the number of cows and sheep began to return to normal, but the refresh frequency of monsters was relatively low.
![)0Q)Z~3(Q(P`ILL271Y3MU3_tmb](https://github.com/KaiijuMC/Kaiiju/assets/131541176/7f3cb2b8-c040-49f0-a8f5-7027bac692ab)
![$5Y_NIBQ~_B0(A1@6}DP 07_tmb](https://github.com/KaiijuMC/Kaiiju/assets/131541176/8fab33a3-7989-44d9-8678-dc643a75d4ba)
This is the picture when set to true

### Plugin and Datapack List

plugins:
[14:47:41 INFO]: Server Plugins (27):
[14:47:41 INFO]: Paper Plugins:
[14:47:41 INFO]:  - HuskHomes
[14:47:41 INFO]: Bukkit Plugins:
[14:47:41 INFO]:  - AntiPopup, Backuper, BetterRTP, BlockLocker, Chunky, CoreProtect, deathmsg1.1, FarmControl, GSit, headdrop
[14:47:41 INFO]:  joinmsg, Kaiivoid, LuckPerms, makefly, MiniMOTD, MiraiMC, PlaceholderAPI, ProtocolLib, SeeMore, TAB
[14:47:41 INFO]:  Towny, TownyChat,Vault, ViaBackwards, ViaRewind, ViaVersion

### Kaiiju version

> version
[14:49:03 INFO]: Checking version, please wait...
[14:49:04 INFO]: This server is running Kaiiju version git-Kaiiju-"daf406e" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: daf406e on dev/1.20.2)
Unknown version

### Other

1.20.2 Is per-player-mob-spawn optimized? Does this option have to be disabled? If it is not disabled, the number of entities will be abnormally large, but there is no such problem in 1.20.1

**Comment by MineSunshineone** [comment]
same maybe paper problem

**Comment by sofianedjerbi** [comment]
Does this still occur on latest commit ?

**Comment by aweibuome** [comment]
Yes, when I ran the last submitted kaiiju server, when I set per-player-mob-spawn to true, a large number of creatures still appeared. The following is the picture
![64763F091D9E1F7182F5F42F31FD26E4](https://github.com/KaiijuMC/Kaiiju/assets/131541176/e6d4026b-e702-4ff8-bcab-80d1426ef11b)
![3FE47BD011A21E9C219829DB2CDB97AA](https://github.com/KaiijuMC/Kaiiju/assets/131541176/9b66e50f-a194-4fed-adb9-eac2e7c5d12c)
![0{QFXQD5SF$I61RICVXZ EW](https://github.com/KaiijuMC/Kaiiju/assets/131541176/f1bbc142-d7e1-4f2b-9c24-b810849b33a7)

![%QAT@EZFC@F @E~7_66L~6V](https://github.com/KaiijuMC/Kaiiju/assets/131541176/e3940da9-b7d7-415f-9f82-400190161ee3)

version:
This server is running Kaiiju version git-Kaiiju-"68de640" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 68de640 on dev/1.20.2)
Unknown version
Previous version: git-Kaiiju-"daf406e" (MC: 1.20.2)

**Comment by sofianedjerbi** [comment]
I can't reproduce this issue, is there any extra information ? (Biome, conditions, number of players..)

**Comment by aweibuome** [comment]
I don't know if this information is valid for you, when I upgraded to 1.20.2 for the first time（
about two days ago）, the number of entities was very large, and when I tried to add some content on the number of creatures in kaiiju-entity-limits.yml, like
GlowSquid:
    limit: 500
    removal: 600,
Something happened, I can’t open the launcher, this is the error message
---- Minecraft Crash Report ----
// Daisy, daisy...// DO NOT REPORT THIS TO PAPER/FOLIA! REPORT TO KAIIJU INSTEAD!Time: 2023-10-13 12:14:34
Description: Exception in server tick loop

org.spongepowered.configurate.serialize.SerializationException: [entities, spawning, monster-spawn-max-light-level] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "default"
	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346)
	at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254)
	at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40)
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151)
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520)
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407)
	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: org.spongepowered.configurate.serialize.SerializationException: [entities, behavior, zombie-villager-infection-chance] of type java.lang.Double: java.lang.NumberFormatException: For input string: "default"
		at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$3(NumericSerializers.java:144)
		... 19 more
	Caused by: java.lang.NumberFormatException: For input string: "default"
		at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
		at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
		at java.base/java.lang.Double.parseDouble(Double.java:651)
		at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$3(NumericSerializers.java:142)
		... 19 more
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 12629875696 bytes (12044 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Microsoft basic display adapter
	Graphics card #0 vendor: (Standard graphics card types) (0x8086)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x9bc5
	Graphics card #0 versionInfo: DriverVersion=10.0.20348.1
	Graphics card #1 name: Microsoft Remote Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.0.20348.1
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37738.02
	Virtual memory used (MB): 16916.17
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 165.05
	JVM Flags: 2 total; -Xms12G -Xmx12G
	CraftBukkit Information: 
   Running: Kaiiju version git-Kaiiju-"daf406e" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Worker-Main-3: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], RUNNABLE Signal Dispatcher: [], WAITING Worker-Main-1: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], RUNNABLE Attach Listener: [], WAITING Worker-Main-4: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Common-Cleaner: [java.base@17.0.8/java.lang.Object.wait(Native Method), java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.8/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.8/java.lang.Thread.run(Thread.java:833), java.base@17.0.8/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], WAITING Tuinity Chunk System Worker #2: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING Finalizer: [java.base@17.0.8/java.lang.Object.wait(Native Method), java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.8/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], RUNNABLE DestroyJavaVM: [], RUNNABLE Notification Thread: [], WAITING Tuinity Chunk System Worker #1: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING RegionFile I/O Thread #0: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], RUNNABLE WindowsStreamPump: [org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(Native Method), org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:138), org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460), org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda$121/0x000001ac84118ac8.run(Unknown Source), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Timer hack thread: [java.base@17.0.8/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$7.run(SystemUtils.java:713)], WAITING Worker-Main-2: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], WAITING Worker-Main-6: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], RUNNABLE Server thread: [java.base@17.0.8/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.8/java.lang.Thread.getAllStackTraces(Thread.java:1662), org.bukkit.craftbukkit.v1_20_R2.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_20_R2.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:62), net.minecraft.CrashReport.<init>(CrashReport.java:38), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1336), net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1280), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343), net.minecraft.server.MinecraftServer$$Lambda$5199/0x000001ac84ae51e0.run(Unknown Source), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.8/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], WAITING Tuinity Chunk System Worker #3: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:82), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:74)], RUNNABLE Reference Handler: [java.base@17.0.8/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.8/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.8/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING Yggdrasil Key Fetcher: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.8/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], WAITING JNA Cleaner: [java.base@17.0.8/java.lang.Object.wait(Native Method), java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)], RUNNABLE ServerMain: [io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.generateBFSOrder(RegionizedPlayerChunkLoader.java:347), io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.<clinit>(RegionizedPlayerChunkLoader.java:389), java.base@17.0.8/java.lang.Class.forName0(Native Method), java.base@17.0.8/java.lang.Class.forName(Class.java:375), org.bukkit.craftbukkit.Main.tryPreloadClass(Main.java:394), org.bukkit.craftbukkit.Main.tryPreloadClass(Main.java:390), org.bukkit.craftbukkit.Main.main(Main.java:383), java.base@17.0.8/java.lang.invoke.LambdaForm$DMH/0x000001ac8400a000.invokeStatic(LambdaForm$DMH), java.base@17.0.8/java.lang.invoke.LambdaForm$MH/0x000001ac8400ac00.invoke(LambdaForm$MH), java.base@17.0.8/java.lang.invoke.LambdaForm$MH/0x000001ac8400a800.invoke_MT(LambdaForm$MH), app//io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42), app//io.papermc.paperclip.Paperclip$$Lambda$10/0x000001ac84001a58.run(Unknown Source), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], WAITING Worker-Main-5: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.8/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465), java.base@17.0.8/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436), java.base@17.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.8/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.8/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Keep-Alive-Timer: [java.base@17.0.8/java.lang.Thread.sleep(Native Method), java.base@17.0.8/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:238), java.base@17.0.8/java.lang.Thread.run(Thread.java:833), java.base@17.0.8/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], WAITING Tuinity Chunk System Worker #0: [java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 88; []
	Data Packs: vanilla, file/bukkit
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'Kaiiju'
	Type: Dedicated Server (map_server.txt)





I deleted the configuration file and regenerated it, but it still didn't work, and I still got this error.
So I opened a new archive and copied the world folder, world_nether folder and world_the_end to the new archive. Fortunately, it can be opened normally.

Some other additional information, the number of players on the server is about 10, and each player joining will add about 3,000 entities.
![(8G GKLQ49C8 BY~2{GPTO](https://github.com/KaiijuMC/Kaiiju/assets/131541176/a05b39ab-531b-40e3-a948-d0acf2fae182)

bukkit.yml:
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 5
  water-ambient: 20
  water-underground-creature: 5
  axolotls: 5
  ambient: 15
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  water-underground-creature-spawns: 1
  axolotl-spawns: 1
  ambient-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml


I don't have any more information because I made almost no changes to the other configurations

The current solution is to set the per-player-mob-spawn option to false. After setting it to false, everything on the server is normal. This is a normal picture.
![GQ0CGR}571~C0VD8AECVSSX](https://github.com/KaiijuMC/Kaiiju/assets/131541176/a8543fca-dc42-463f-bf51-a8f87c55b58e)

**Comment by aweibuome** [comment]
I want to know if other people who use kaiiju1.20.2 have the same problem as me. If not, maybe there is an error in my own archive,and you can close this issue.

**Comment by MineSunshineone** [comment]
> 我想知道其他使用 kaiiju1.20.2 的人是否和我有同样的问题。如果没有，也许我自己的存档中有错误，您可以关闭此问题。

same problem

**Comment by starmc63** [comment]
让我看看你的草莓

**Comment by sofianedjerbi** [comment]
confirmed as a folia bug
